version: "3"

services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client.dev
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server.dev
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
