# Dockerfile.server.dev
FROM node:16

WORKDIR /app

# Node.js の依存関係をインストール
COPY server/package*.json ./
RUN npm install

# サーバーコードをコピー
COPY server/ ./

# サーバーを起動
CMD ["node", "server.js"]
