version: "3"

services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client.prod
    ports:
      - "80:80"
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server.prod
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
